[package]
name = "udd-conv-cli"
version = "0.1.0"
edition = "2024"
#resolver = "3"
autobins = false

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
csv.workspace = true
image = { workspace = true, features = ["png"] }
log.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
knuffel.workspace = true
toml.workspace = true
udd-assets = { path = "../../lib/udd-assets" }
udd-container = { path = "../../lib/udd-container" }
udd-conv = { path = "../../lib/udd-conv" }
udd-image-codecs = { path = "../../lib/udd-image-codecs", features = ["ktx2"] }
udd-logging = { path = "../../lib/udd-logging" }
uocf = { path = "../../lib/uocf" }

[features]
default = []

[[bin]]
name = "udd-cli"
path = "src/bin/uddcli.rs"
