input_uddp_dir = "packages"
output_uddp_dir = "packages"
link_uddp_dirs = true
bc7_cc_art = false
bc7_ec_art = false
bc7_ec_land = false
planar_cc_art = true
planar_ec_art = false
planar_ec_land = false
radar_format = "Bc7"
radar_zstd = 3
