[package]
name = "udd-container"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"

[dependencies]
xxhash-rust = { version = "0.8", default-features = false, features = ["xxh64"] }
zstd.workspace = true
jpegxl-rs = { version = "0.14", features = ["vendored"] }
byteorder.workspace = true
rayon.workspace = true
memmap2 = "0.9"

#[lib]
#crate-type = ["dylib", "rlib"]
