[package]
name = "uocf-inspector-gui"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
items_after_test_module = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_range_loop = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
image = { workspace = true, features = ["png"] }
image-postprocess = { path = "../../lib/image-postprocess" }
udd-conv = { path = "../../lib/udd-conv" }
udd-assets = { path = "../../lib/udd-assets" }
udd-image-codecs = { path = "../../lib/udd-image-codecs", features = ["ktx2"] }
uocf = { path = "../../lib/uocf" }
rfd.workspace = true
udd-logging = { path = "../../lib/udd-logging" }
gui-shared = { path = "../../lib/gui-shared" }
rodio.workspace = true
serde.workspace = true
color-eyre.workspace = true
knuffel.workspace = true
log.workspace = true
