[package]
name = "image-postprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png"] }
serde = { version = "1.0", features = ["derive"] }
xbrz-rs = "0.1.0"
hqx = { git = "https://github.com/CryZe/wasmboy-rs" }
mmpx = "0.2.0"
bcdec_rs = "0.2"
wide = "1.4"

[package.metadata.cargo-machete]
ignored = ["xbrz-rs"]
