[package]
name = "image-postprocess"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
if_same_then_else = "allow"
manual_clamp = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
needless_range_loop = "allow"
nonminimal_bool = "allow"
overly_complex_bool_expr = "allow"
too_many_arguments = "allow"

[dependencies]
image = { version = "0.25", default-features = false }
serde = { version = "1.0", features = ["derive"] }
xbrz-rs = "0.1.0"
hqx = { git = "https://github.com/CryZe/wasmboy-rs" }
wide = { version = "1.5", default-features = false, features = ["std"] }

[package.metadata.cargo-machete]
ignored = ["xbrz-rs"]
