[package]
name = "uoppackage-cli"
version = "0.1.0"
edition = "2024"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"

[dependencies]
uocf = { path = "../../lib/uocf" }
udd-logging = { path = "../../lib/udd-logging" }
clap = { workspace = true, features = ["derive", "unicode"] }
color-eyre.workspace = true
flate2.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }
toml.workspace = true

[[bin]]
name = "uoppackage-cli"
path = "src/main.rs"
