[package]
name = "uddp-inspector-gui"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
manual_div_ceil = "allow"
manual_clamp = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
redundant_locals = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

[lints.rust]
dead_code = "allow"

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
uocf = { path = "../../lib/uocf" }
udd-assets = { path = "../../lib/udd-assets" }
udd-conv = { path = "../../lib/udd-conv" }
udd-container = { path = "../../lib/udd-container" }
ktx2.workspace = true
zstd.workspace = true
color-eyre.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
rfd.workspace = true
byteorder = "1.5"
serde = { version = "1", features = ["derive"] }
bytemuck = { version = "1.*", default-features = false, features = ["derive", "aarch64_simd", "avx512_simd"] }
image = { version = "0.25", default-features = false, features = [
    "png",
    "dds",
    "tga",
    "bmp",
] }
