[package]
name = "udd-conv-gui"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[dependencies]
eframe = { version = "0.31.1", default-features = false, features = [
    "default_fonts",
    "wayland",
    "wgpu",
    "x11",
    "persistence",
    "glow",
] }
egui = { version = "0.31.1", features = [ "bytemuck" ] }
egui_extras = { version = "0.31.1", features = ["image"] }
rfd = { version = "0.15", features = ["xdg-portal"] }
color-eyre = "0.6.5"
libc = "0.2"
log = "0.4.29"
udd-conv = { path = "../../lib/udd-conv" }
udd-image-codecs = { path = "../../lib/udd-image-codecs", features = ["ktx2"] }
udd-logging = { path = "../../lib/udd-logging" }
uocf = { path = "../../lib/uocf" }
udd-conv-cli = { path = "../udd-conv-cli" }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "1.1", default-features = false, features = ["display", "parse", "serde"] }
ktx2 = "0.4"
image = { version = "0.25", default-features = false, features = ["png", "dds"] }
zstd.workspace = true

[features]
default = []

[[bin]]
name = "udd-conv-gui"
path = "src/main.rs"
