[package]
name = "udd-conv-gui"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
field_reassign_with_default = "allow"
manual_clamp = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"

[dependencies]
eframe.workspace = true
egui.workspace = true
egui_extras.workspace = true
rfd.workspace = true
color-eyre.workspace = true
libc = "0.2"
log = "0.4.32"
udd-conv = { path = "../../lib/udd-conv" }
udd-image-codecs = { path = "../../lib/udd-image-codecs", features = ["ktx2"] }
udd-logging = { path = "../../lib/udd-logging" }
uocf = { path = "../../lib/uocf" }
udd-conv-cli = { path = "../udd-conv-cli" }
tokio = { version = "1.52", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
toml.workspace = true
ktx2.workspace = true
image = { version = "0.25", default-features = false, features = ["png", "dds"] }
zstd.workspace = true

[features]
default = []

[[bin]]
name = "udd-conv-gui"
path = "src/main.rs"
