cc_dir = "/mnt/dati/_proj_local/_uo_clients/_Ultima Online Classic"
ec_dir = "/mnt/dati/_proj_local/_uo_clients/_Ultima Online Enhanced/"
input_uddp_dir = "/home/claudio/test/uddp_gui"
output_uddp_dir = "/home/claudio/test/uddp_gui"
link_uddp_dirs = true
opt_cc_art = "None"
opt_ec_art = "JpegXl"
opt_ec_land = "None"
radar_format = "Bc7"
radar_zstd = 3
