# Core settings for UODynamapper
# These are strictly engine/system level and usually don't change often.

[core.world]
# Default starting position in UO coordinates [X, Y, Z, MapID]
start_p = [1100, 1800, 20, 0]
# Whether to hide the player cube on startup
hide_player = false

[logging]
# Minimum log level to display in terminal
min_severity = "Info"

# Custom filters for specific modules or severities
[[logging.filters]]
about = "RenderWorldLand"
suppress = true

#[[logging.filters]]
#sev = "Debug"
#suppress = false
