[package]
name = "udd-image-codecs"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
arc_with_non_send_sync = "allow"
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"


[dependencies]
color-eyre = { workspace = true, optional = true }
dds.workspace = true
ktx2 = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
wgpu-types.workspace = true
wide = { version = "1.5", optional = true }
zstd = { workspace = true, optional = true }

[features]
default = []
bc7-encode = ["dep:rayon", "dep:wide"]
ktx2 = ["dep:color-eyre", "dep:ktx2", "dep:zstd"]

[[bench]]
name = "bc7_encode"
harness = false
required-features = ["bc7-encode"]
