[core.world]
hide_player = true

[core.world.start_p]
x = 5722
y = 2991
z = 0
m = 0

[logging]
min_severity = "Debug"
emit_flat_plugin_build = false
emit_tree_plugin_build = true

[[logging.filters]]
sev = "Debug"
suppress = false

[[logging.filters]]
sev = "DebugVerbose"
suppress = false

[[logging.filters]]
about = "RenderWorldLand"
suppress = false

[[logging.filters]]
sev = "Debug"
about = "Startup"
suppress = true

[[logging.filters]]
sev = "Debug"
about = "Performance"
suppress = true

[[logging.filters]]
about = "Performance"
suppress = false
