[graphics]
lossy_texture_compression = false
lossy_texture_compression_backend = "dds"
reduce_unfocused_fps = true
vsync = false
anti_aliasing = "off"
art_texture_source = "ec"
land_texture_source = "ec"
sharpening_strength = 0.0
