# Map dimensions in tiles.
#
# Edit these entries if your client uses custom-sized map files.
# map0/map1 are set to the default Mondain's Legacy sizes.
# If you are using a pre-ML client, map0/map1 can be changed to 6144x4096.

[[maps]]
id = 0
width = 7168
height = 4096

[[maps]]
id = 1
width = 7168
height = 4096

[[maps]]
id = 2
width = 2304
height = 1600

[[maps]]
id = 3
width = 2560
height = 2048

[[maps]]
id = 4
width = 1448
height = 1448

[[maps]]
id = 5
width = 1280
height = 4096
