[package]
name = "uocf_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
uocf = { path = "../uocf" }
color-eyre = "0.6.5"
anyhow = "1.0.102"
byteorder = "1.5.0"
flate2 = "1.1.9"
env_logger = "0.11.10"
log = "0.4.29"

[[bin]]
name = "uoptool"
path = "src/bin/uoptool.rs"

[[bin]]
name = "cc_uop_mul_converter"
path = "src/bin/cc_uop_mul_converter.rs"
