# -- Local
[build]
target-dir = "/home/claudio/_builds"

# -- Unstable Rust compiler only, but useful for profiling.
#[unstable]
#profile-rustflags = true

#[profile.profiling]
#rustflags = ["-C", "force-frame-pointers=yes"]

# ----------

# -- Linux, GNU libc (default)
[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.'cfg(all(target_os = "linux", debug_assertions, not(feature = "profiling")))']
# wild linker (even faster than mold) + frame-pointers for debug
#rustflags = ["-Clink-arg=-fuse-ld=wild", "-C", "force-frame-pointers=yes"]
rustflags = ["-Clink-arg=-fuse-ld=mold", "-C", "force-frame-pointers=yes"]

[target.'cfg(all(target_os = "linux", feature = "profiling"))']
# profiling feature enables frame pointers (applies to crates with the feature)
rustflags = ["-Clink-arg=-fuse-ld=mold", "-C", "force-frame-pointers=yes"]

[target.'cfg(all(target_os = "linux", not(debug_assertions)))']
# mold linker for release
rustflags = ["-Clink-arg=-fuse-ld=mold"]

# -- Linux, Musl libc (statically linked)
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-self-contained=yes",
]
#linker = "musl-gcc"

[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C",
  "target-feature=+crt-static",
  "-C",
  "link-self-contained=yes",
]
#linker = "aarch64-linux-musl-gcc"

# -- Windows
# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.x86_64-pc-windows-msvc]
#linker = "rust-lld.exe"
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
#linker = "rust-lld.exe"
rustflags = ["-C", "target-feature=+crt-static"]
