# -- Local
[build]
target-dir = "target"
#target-dir = "/home/claudio/_builds/"

# -- Unstable Rust toolchain only. Only Cargo flags are supported here, not rustc.
#[unstable]
#no-embed-metadata = true
#profile-rustflags = true

#[profile.profiling]
#rustflags = ["-C", "force-frame-pointers=yes"]

# !!!!!!!!!!
# The following flags are meant to be used for rapid/local testing and prototyping with "debug" builds, so that
#  we don't have cmdline flags bloat. Moreover (most importantly, even), the agents can simply use "cargo", which
#  will use the sane defaults we are setting here.
# For profiling or release builds we centralize flags management in the "justfile" and use "just"
#  to compile those optimized builds with the proper cargo, rustc and compiler flags,
# for both nightly (reccomended) and stable Rust toolchains.
# !!!!!!!!!!


# ----------
# Linux, GNU libc (default)
# ----------

[target.x86_64-unknown-linux-gnu]
linker = "clang"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.'cfg(target_os = "linux")']
# wild linker (even faster than mold) + frame-pointers for debug
rustflags = [
  # rustc flags
  "-C", "force-frame-pointers=yes",
  "-C", "embed-bitcode=no",
  # linker flags
  "-Clink-arg=-fuse-ld=wild", # "-Clink-arg=-fuse-ld=mold",
  "-Clink-arg=-Wl,--gc-sections",
]

# ----------
# macos
# ----------

[target.'cfg(target_os = "macos")']
rustflags = [
  # rustc flags
  "-C", "force-frame-pointers=yes",
  "-C", "embed-bitcode=no",
  # linker flags
  "-Clink-arg=-Wl,-dead_strip",
]


# ----------
# Windows
# ----------

# On Windows MSVC, we can statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.'cfg(target_os = "windows")']
#linker = "rust-lld.exe"
rustflags = [
  # rustc flags
  "-C", "force-frame-pointers=yes",
  #"-C", "target-feature=+crt-static",
  "-C", "embed-bitcode=no",
  # linker flags
  "-Clink-arg=-Wl,--gc-sections",
]

