[package]
name = "uocf-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
uocf = { path = "../../lib/uocf" }
color-eyre = "0.6.5"
byteorder = { version = "1.5.0", default-features = false }
flate2 = { version = "1.1.9", default-features = false }
env_logger = "0.11.10"
log = "0.4.29"
walkdir = "2.5.0"
csv = "1.4.0"
dds = { version = "0.2", default-features = false }
ddsfile = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
indicatif = "0.17"

[[bin]]
name = "uop-tool"
path = "src/bin/uoptool.rs"

[[bin]]
name = "cc-uop-mul-converter"
path = "src/bin/cc_uop_mul_converter.rs"

[[bin]]
name = "uop-dict-populator-cli"
path = "src/bin/uop_dict_populator.rs"

[[bin]]
name = "texture-scanner"
path = "src/bin/dev-tools/texture_scanner.rs"

[[bin]]
name = "sound-tool"
path = "src/bin/sound_tool.rs"

[[bin]]
name = "multimap-tool"
path = "src/bin/multimap_tool.rs"

[[bin]]
name = "facet-evidence-tool"
path = "src/bin/facet_evidence_tool.rs"
