[uo_files]
folder="/mnt/dati/_proj_local/_uo_clients/Ultima Online Mondain's Legacy/"

[input]
movement_speed_multiplier=1.0 # 100.0

[window]
height=768.0
width=1024.0
zoom=1.0

[world]
start_p=[1100,1800,20,0]

#[scene]
#hide_player=false
#brightness=20 # 1-25
#fog=0 # 0-100
#saturation_factor=1 # 0.0-10.0?

[debug]
map_render_wireframe=false
#print_land_mesh_stats=false
#print_land_mesh_period=5.0 # seconds

#[logger]
#ignore=[
    # Uses a regex for the match.
    # [Severity, About]
    #["Debug",            ".*"],
    #["InternalVerbose1", ".*"],
#    ["InternalVerbose2", "*"],
#]
