[package]
name = "uocf-asset-cli"
version = "0.1.0"
edition = "2024"

[lints.clippy]
too_many_arguments = "allow"

[dependencies]
uocf = { path = "../../lib/uocf" }
clap = { workspace = true, features = ["derive", "unicode"] }
color-eyre.workspace = true
udd-logging = { path = "../../lib/udd-logging" }

[[bin]]
name = "uocf-asset-cli"
path = "src/main.rs"
