[package]
name = "udd-assets"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comments = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

[dependencies]
udd-container = { path = "../udd-container" }
udd-image-codecs = { path = "../udd-image-codecs" }
uocf = { path = "../uocf" }
bytemuck.workspace = true
color-eyre.workspace = true
byteorder.workspace = true
knuffel.workspace = true
serde_json.workspace = true
dds.workspace = true

[features]
default = []
bc7-encode = ["udd-image-codecs/bc7-encode"]

#[lib]
#crate-type = ["dylib", "rlib"]
