[package]
name = "udd-assets"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[dependencies]
udd-container = { path = "../udd-container" }
udd-image-codecs = { path = "../udd-image-codecs" }
uocf = { path = "../uocf" }
bytemuck = { version = "1.*", default-features = false, features = ["derive", "aarch64_simd", "avx512_simd"] }
color-eyre = "0.6"
byteorder = "1.5"
knuffel = "3"
serde_json = "1"
dds = "0.2"

[features]
default = []
bc7-encode = ["udd-image-codecs/bc7-encode"]
