# Cargo.toml
[package]
name = "uocf"
version = "0.0.1"
edition = "2024"

[lints.clippy]
needless_lifetimes = "allow"
collapsible_if = "allow"
manual_is_multiple_of = "allow"
too_many_arguments = "allow"

[dependencies]
byteorder = "1.5"
color-eyre = { version = "0.6", default-features = false, features = ["track-caller"] }
derive-new = "0.7"
getset = "0.1"
glam = { version = "0.30", default-features = false, features = ["std"] }
image = { version = "0.25", default-features = false, features = ["bmp", "dds"] }
wide = { version = "1", features = ["std"] }
bytemuck = { version = "1", features = ["derive"] }
smallvec = "1"
