[package]
name = "uop-dict-populator-gui"
version = "0.1.0"
edition = "2024"
#resolver = "3"

[lints.clippy]
collapsible_if = "allow"
empty_line_after_doc_comment = "allow"
manual_div_ceil = "allow"
manual_is_multiple_of = "allow"
needless_lifetimes = "allow"
nonminimal_bool = "allow"

[dependencies]
eframe = { version = "0.31.1", default-features = false, features = [
    "default_fonts",
    "wayland",
    "wgpu",
    "x11",
    "persistence",
    "glow",
] }
egui = { version = "0.31.1", features = [ "bytemuck" ] }
egui_extras = { version = "0.31.1", features = ["all_loaders"] }
uocf = { path = "../../lib/uocf" }
rfd = { version = "0.15", features = ["xdg-portal"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
udd-logging = { path = "../../lib/udd-logging" }
color-eyre = "0.6"
crossbeam-channel = "0.5"
