[package]
name = "uddp_inspector"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31.0", features = ["persistence"] }
egui_extras = { version = "0.31.0", features = ["all_loaders"] }
uocf = { path = "../uocf" }
uddconv = { path = "../uddconv" }
ktx2 = "0.4"
zstd = "0.13"
color-eyre = "0.6"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
rfd = { version = "0.15", features = ["xdg-portal"] }
byteorder = "1.5"
serde = { version = "1", features = ["derive"] }
toml = { version = "1.1", default-features = false, features = ["display", "parse", "serde"] }
bytemuck = "1.16"
image = { version = "0.25", default-features = false, features = [
    "png",
    "jpeg",
    "dds",
    "tga",
    "bmp",
] }
egui = "0.31.0"
